#print("enter first number")
#n1=input()
#print("enter second number")
#n2=input()
#print("sum of these numbers is", int(n1) + int(n2))
#n3=input()
#print("enter third number")
#n4=input()
#print("enter fourth number")
#print("divide of this number", int(n3)/int(n4))
#print("enter third number")
#n5=input()
#print("enter fourth number")
#n6=input()
#print("module of this number",int(n5)%int(n6))
x="2.0"
print(type(x))
